/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1.134
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.CampaignMappingPaginationResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CampaignMappingApi
 */
@Ignore
public class CampaignMappingApiTest {

    private final CampaignMappingApi api = new CampaignMappingApi();

    /**
     * 
     *
     * Remove a campaign mapping.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMappingDeleteTest() throws Exception {
        String id = null;
        api.campaignMappingDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search campaign mapping.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMappingSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        CampaignMappingPaginationResponse response = api.campaignMappingSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
}
