/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: STATFLO-3851-Sms-Activity
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.Consent;
import com.statflo.client.model.ConsentCreate;
import com.statflo.client.model.ConsentPaginationResponse;
import com.statflo.client.model.ConsentUpdate;
import com.statflo.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ConsentApi
 */
@Ignore
public class ConsentApiTest {

    private final ConsentApi api = new ConsentApi();

    /**
     * 
     *
     * Create consent
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consentCreateTest() throws Exception {
        ConsentCreate body = null;
        Consent response = api.consentCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove an consent
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consentDeleteTest() throws Exception {
        String id = null;
        api.consentDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve an consent
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consentGetTest() throws Exception {
        String id = null;
        Consent response = api.consentGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search consent
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consentSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        ConsentPaginationResponse response = api.consentSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update an consent
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consentUpdateTest() throws Exception {
        String id = null;
        ConsentUpdate body = null;
        Consent response = api.consentUpdate(id, body);

        // TODO: test validations
    }
}
