/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: main
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.ErrorResponse;
import com.statflo.client.model.MessageDeliveryStatus;
import com.statflo.client.model.MessageDeliveryStatusCreate;
import com.statflo.client.model.MessageDeliveryStatusPaginationResponse;
import com.statflo.client.model.MessageDeliveryStatusUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MessageDeliveryStatusApi
 */
@Ignore
public class MessageDeliveryStatusApiTest {

    private final MessageDeliveryStatusApi api = new MessageDeliveryStatusApi();

    /**
     * 
     *
     * Create a message delivery status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void messageDeliveryStatusCreateTest() throws Exception {
        MessageDeliveryStatusCreate body = null;
        MessageDeliveryStatus response = api.messageDeliveryStatusCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove a Message Delivery Status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void messageDeliveryStatusDeleteTest() throws Exception {
        String id = null;
        api.messageDeliveryStatusDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve message delivery status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void messageDeliveryStatusGetTest() throws Exception {
        String id = null;
        MessageDeliveryStatus response = api.messageDeliveryStatusGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search message delivery status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void messageDeliveryStatusSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        MessageDeliveryStatusPaginationResponse response = api.messageDeliveryStatusSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update a message delivery status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void messageDeliveryStatusUpdateTest() throws Exception {
        String id = null;
        MessageDeliveryStatusUpdate body = null;
        MessageDeliveryStatus response = api.messageDeliveryStatusUpdate(id, body);

        // TODO: test validations
    }
}
