/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1.191
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.ErrorResponse;
import com.statflo.client.model.RCSAgentMetadata;
import com.statflo.client.model.RCSAgentMetadataCreate;
import com.statflo.client.model.RCSAgentMetadataPaginationResponse;
import com.statflo.client.model.RCSAgentMetadataUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RcsAgentMetadataApi
 */
@Ignore
public class RcsAgentMetadataApiTest {

    private final RcsAgentMetadataApi api = new RcsAgentMetadataApi();

    /**
     * 
     *
     * Create an rcs agent metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rCSAgentMetadataCreateTest() throws Exception {
        RCSAgentMetadataCreate body = null;
        RCSAgentMetadata response = api.rCSAgentMetadataCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove an rcs agent metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rCSAgentMetadataDeleteTest() throws Exception {
        String id = null;
        api.rCSAgentMetadataDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve an rcs agent metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rCSAgentMetadataGetTest() throws Exception {
        String id = null;
        RCSAgentMetadata response = api.rCSAgentMetadataGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search rcs agent metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rCSAgentMetadataSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        RCSAgentMetadataPaginationResponse response = api.rCSAgentMetadataSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update an rcs agent metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rCSAgentMetadataUpdateTest() throws Exception {
        String id = null;
        RCSAgentMetadataUpdate body = null;
        RCSAgentMetadata response = api.rCSAgentMetadataUpdate(id, body);

        // TODO: test validations
    }
}
