/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: main
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.ErrorResponse;
import com.statflo.client.model.Timeline;
import com.statflo.client.model.TimelineCreate;
import com.statflo.client.model.TimelinePaginationResponse;
import com.statflo.client.model.TimelineUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TimelinesApi
 */
@Ignore
public class TimelinesApiTest {

    private final TimelinesApi api = new TimelinesApi();

    /**
     * 
     *
     * Create an timeline.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void timelineCreateTest() throws Exception {
        TimelineCreate body = null;
        Timeline response = api.timelineCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove an timeline.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void timelineDeleteTest() throws Exception {
        String id = null;
        api.timelineDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve an timeline.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void timelineGetTest() throws Exception {
        String id = null;
        Timeline response = api.timelineGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search timelines.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void timelineSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        TimelinePaginationResponse response = api.timelineSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update an timeline.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void timelineUpdateTest() throws Exception {
        String id = null;
        TimelineUpdate body = null;
        Timeline response = api.timelineUpdate(id, body);

        // TODO: test validations
    }
}
