/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1.167
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.api;

import com.statflo.client.model.UserMetadata;
import com.statflo.client.model.UserMetadataCreate;
import com.statflo.client.model.UserMetadataPaginationResponse;
import com.statflo.client.model.UserMetadataUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserMetadataApi
 */
@Ignore
public class UserMetadataApiTest {

    private final UserMetadataApi api = new UserMetadataApi();

    /**
     * 
     *
     * Create a user metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userMetadataCreateTest() throws Exception {
        UserMetadataCreate body = null;
        UserMetadata response = api.userMetadataCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove a user metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userMetadataDeleteTest() throws Exception {
        String id = null;
        api.userMetadataDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve a user metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userMetadataGetTest() throws Exception {
        String id = null;
        UserMetadata response = api.userMetadataGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search user metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userMetadataSearchTest() throws Exception {
        java.util.HashMap filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        UserMetadataPaginationResponse response = api.userMetadataSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update a user metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userMetadataUpdateTest() throws Exception {
        String id = null;
        UserMetadataUpdate body = null;
        UserMetadata response = api.userMetadataUpdate(id, body);

        // TODO: test validations
    }
}
