/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: STATFLO-3851-Sms-Activity
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.statflo.client.model.AccountNumber;
import com.statflo.client.model.Pagination;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AccountNumberPaginationResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-26T16:29:28.478698-05:00[America/Toronto]")

public class AccountNumberPaginationResponse {
  @SerializedName("items")
  private List<AccountNumber> items = null;

  @SerializedName("pagination")
  private Pagination pagination = null;

  @SerializedName("aggregations")
  private java.util.HashMap aggregations = null;

  public AccountNumberPaginationResponse items(List<AccountNumber> items) {
    this.items = items;
    return this;
  }

  public AccountNumberPaginationResponse addItemsItem(AccountNumber itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Schema(description = "")
  public List<AccountNumber> getItems() {
    return items;
  }

  public void setItems(List<AccountNumber> items) {
    this.items = items;
  }

  public AccountNumberPaginationResponse pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @Schema(description = "")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public AccountNumberPaginationResponse aggregations(java.util.HashMap aggregations) {
    this.aggregations = aggregations;
    return this;
  }

   /**
   * Get aggregations
   * @return aggregations
  **/
  @Schema(description = "")
  public java.util.HashMap getAggregations() {
    return aggregations;
  }

  public void setAggregations(java.util.HashMap aggregations) {
    this.aggregations = aggregations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountNumberPaginationResponse accountNumberPaginationResponse = (AccountNumberPaginationResponse) o;
    return Objects.equals(this.items, accountNumberPaginationResponse.items) &&
        Objects.equals(this.pagination, accountNumberPaginationResponse.pagination) &&
        Objects.equals(this.aggregations, accountNumberPaginationResponse.aggregations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, pagination, aggregations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountNumberPaginationResponse {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    aggregations: ").append(toIndentedString(aggregations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
