/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1.192
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.statflo.client.model.Carrier;
import com.statflo.client.model.Dealer;
import com.statflo.client.model.RCSAgentBusiness;
import com.statflo.client.model.RCSAgentUseCase;
import com.statflo.client.model.User;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * RCSAgent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-05T17:21:51.687746289Z[Etc/UTC]")

public class RCSAgent {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("applicationName")
  private String applicationName = null;

  @SerializedName("senderId")
  private String senderId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("logoUrl")
  private String logoUrl = null;

  @SerializedName("bannerUrl")
  private String bannerUrl = null;

  @SerializedName("privacyUrl")
  private String privacyUrl = null;

  @SerializedName("termsOfServiceUrl")
  private String termsOfServiceUrl = null;

  @SerializedName("accentColor")
  private String accentColor = null;

  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("callbackMethod")
  private String callbackMethod = null;

  @SerializedName("fallbackUrl")
  private String fallbackUrl = null;

  @SerializedName("fallbackMethod")
  private String fallbackMethod = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("repUser")
  private User repUser = null;

  @SerializedName("website")
  private List<Object> website = new ArrayList<>();

  @SerializedName("email")
  private List<Object> email = new ArrayList<>();

  @SerializedName("phoneNumber")
  private List<Object> phoneNumber = new ArrayList<>();

  @SerializedName("regulationId")
  private String regulationId = "RN285c55a933ea017bdc9c0d6e6ad1ce00";

  @SerializedName("regulationVersion")
  private Integer regulationVersion = 1;

  @SerializedName("usRegulationId")
  private String usRegulationId = "RN3038ea6be8e9792456beb40f0a18695d";

  @SerializedName("usRegulationVersion")
  private Integer usRegulationVersion = 1;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("friendlyName")
  private String friendlyName = null;

  @SerializedName("statusNotificationEmail")
  private String statusNotificationEmail = null;

  @SerializedName("statusCallbackUrl")
  private String statusCallbackUrl = null;

  @SerializedName("sid")
  private String sid = null;

  @SerializedName("registrationSid")
  private String registrationSid = null;

  @SerializedName("googleRegistrationSid")
  private String googleRegistrationSid = null;

  @SerializedName("addressSid")
  private String addressSid = null;

  @SerializedName("user")
  private User user = null;

  @SerializedName("carrier")
  private Carrier carrier = null;

  @SerializedName("dealer")
  private Dealer dealer = null;

  @SerializedName("rcsAgentUseCase")
  private RCSAgentUseCase rcsAgentUseCase = null;

  @SerializedName("rcsAgentBusiness")
  private RCSAgentBusiness rcsAgentBusiness = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  public RCSAgent id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public RCSAgent applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @Schema(required = true, description = "")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }

  public RCSAgent senderId(String senderId) {
    this.senderId = senderId;
    return this;
  }

   /**
   * Get senderId
   * @return senderId
  **/
  @Schema(required = true, description = "")
  public String getSenderId() {
    return senderId;
  }

  public void setSenderId(String senderId) {
    this.senderId = senderId;
  }

  public RCSAgent name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RCSAgent description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RCSAgent logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @Schema(required = true, description = "")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public RCSAgent bannerUrl(String bannerUrl) {
    this.bannerUrl = bannerUrl;
    return this;
  }

   /**
   * Get bannerUrl
   * @return bannerUrl
  **/
  @Schema(required = true, description = "")
  public String getBannerUrl() {
    return bannerUrl;
  }

  public void setBannerUrl(String bannerUrl) {
    this.bannerUrl = bannerUrl;
  }

  public RCSAgent privacyUrl(String privacyUrl) {
    this.privacyUrl = privacyUrl;
    return this;
  }

   /**
   * Get privacyUrl
   * @return privacyUrl
  **/
  @Schema(required = true, description = "")
  public String getPrivacyUrl() {
    return privacyUrl;
  }

  public void setPrivacyUrl(String privacyUrl) {
    this.privacyUrl = privacyUrl;
  }

  public RCSAgent termsOfServiceUrl(String termsOfServiceUrl) {
    this.termsOfServiceUrl = termsOfServiceUrl;
    return this;
  }

   /**
   * Get termsOfServiceUrl
   * @return termsOfServiceUrl
  **/
  @Schema(required = true, description = "")
  public String getTermsOfServiceUrl() {
    return termsOfServiceUrl;
  }

  public void setTermsOfServiceUrl(String termsOfServiceUrl) {
    this.termsOfServiceUrl = termsOfServiceUrl;
  }

  public RCSAgent accentColor(String accentColor) {
    this.accentColor = accentColor;
    return this;
  }

   /**
   * Get accentColor
   * @return accentColor
  **/
  @Schema(required = true, description = "")
  public String getAccentColor() {
    return accentColor;
  }

  public void setAccentColor(String accentColor) {
    this.accentColor = accentColor;
  }

  public RCSAgent callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @Schema(required = true, description = "")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public RCSAgent callbackMethod(String callbackMethod) {
    this.callbackMethod = callbackMethod;
    return this;
  }

   /**
   * Get callbackMethod
   * @return callbackMethod
  **/
  @Schema(required = true, description = "")
  public String getCallbackMethod() {
    return callbackMethod;
  }

  public void setCallbackMethod(String callbackMethod) {
    this.callbackMethod = callbackMethod;
  }

  public RCSAgent fallbackUrl(String fallbackUrl) {
    this.fallbackUrl = fallbackUrl;
    return this;
  }

   /**
   * Get fallbackUrl
   * @return fallbackUrl
  **/
  @Schema(required = true, description = "")
  public String getFallbackUrl() {
    return fallbackUrl;
  }

  public void setFallbackUrl(String fallbackUrl) {
    this.fallbackUrl = fallbackUrl;
  }

  public RCSAgent fallbackMethod(String fallbackMethod) {
    this.fallbackMethod = fallbackMethod;
    return this;
  }

   /**
   * Get fallbackMethod
   * @return fallbackMethod
  **/
  @Schema(required = true, description = "")
  public String getFallbackMethod() {
    return fallbackMethod;
  }

  public void setFallbackMethod(String fallbackMethod) {
    this.fallbackMethod = fallbackMethod;
  }

  public RCSAgent status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public RCSAgent repUser(User repUser) {
    this.repUser = repUser;
    return this;
  }

   /**
   * Get repUser
   * @return repUser
  **/
  @Schema(description = "")
  public User getRepUser() {
    return repUser;
  }

  public void setRepUser(User repUser) {
    this.repUser = repUser;
  }

  public RCSAgent website(List<Object> website) {
    this.website = website;
    return this;
  }

  public RCSAgent addWebsiteItem(Object websiteItem) {
    this.website.add(websiteItem);
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @Schema(required = true, description = "")
  public List<Object> getWebsite() {
    return website;
  }

  public void setWebsite(List<Object> website) {
    this.website = website;
  }

  public RCSAgent email(List<Object> email) {
    this.email = email;
    return this;
  }

  public RCSAgent addEmailItem(Object emailItem) {
    this.email.add(emailItem);
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(required = true, description = "")
  public List<Object> getEmail() {
    return email;
  }

  public void setEmail(List<Object> email) {
    this.email = email;
  }

  public RCSAgent phoneNumber(List<Object> phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  public RCSAgent addPhoneNumberItem(Object phoneNumberItem) {
    this.phoneNumber.add(phoneNumberItem);
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @Schema(required = true, description = "")
  public List<Object> getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(List<Object> phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public RCSAgent regulationId(String regulationId) {
    this.regulationId = regulationId;
    return this;
  }

   /**
   * Get regulationId
   * @return regulationId
  **/
  @Schema(description = "")
  public String getRegulationId() {
    return regulationId;
  }

  public void setRegulationId(String regulationId) {
    this.regulationId = regulationId;
  }

  public RCSAgent regulationVersion(Integer regulationVersion) {
    this.regulationVersion = regulationVersion;
    return this;
  }

   /**
   * Get regulationVersion
   * @return regulationVersion
  **/
  @Schema(description = "")
  public Integer getRegulationVersion() {
    return regulationVersion;
  }

  public void setRegulationVersion(Integer regulationVersion) {
    this.regulationVersion = regulationVersion;
  }

  public RCSAgent usRegulationId(String usRegulationId) {
    this.usRegulationId = usRegulationId;
    return this;
  }

   /**
   * Get usRegulationId
   * @return usRegulationId
  **/
  @Schema(description = "")
  public String getUsRegulationId() {
    return usRegulationId;
  }

  public void setUsRegulationId(String usRegulationId) {
    this.usRegulationId = usRegulationId;
  }

  public RCSAgent usRegulationVersion(Integer usRegulationVersion) {
    this.usRegulationVersion = usRegulationVersion;
    return this;
  }

   /**
   * Get usRegulationVersion
   * @return usRegulationVersion
  **/
  @Schema(description = "")
  public Integer getUsRegulationVersion() {
    return usRegulationVersion;
  }

  public void setUsRegulationVersion(Integer usRegulationVersion) {
    this.usRegulationVersion = usRegulationVersion;
  }

  public RCSAgent comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public RCSAgent friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

   /**
   * Get friendlyName
   * @return friendlyName
  **/
  @Schema(description = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public RCSAgent statusNotificationEmail(String statusNotificationEmail) {
    this.statusNotificationEmail = statusNotificationEmail;
    return this;
  }

   /**
   * Get statusNotificationEmail
   * @return statusNotificationEmail
  **/
  @Schema(description = "")
  public String getStatusNotificationEmail() {
    return statusNotificationEmail;
  }

  public void setStatusNotificationEmail(String statusNotificationEmail) {
    this.statusNotificationEmail = statusNotificationEmail;
  }

  public RCSAgent statusCallbackUrl(String statusCallbackUrl) {
    this.statusCallbackUrl = statusCallbackUrl;
    return this;
  }

   /**
   * Get statusCallbackUrl
   * @return statusCallbackUrl
  **/
  @Schema(description = "")
  public String getStatusCallbackUrl() {
    return statusCallbackUrl;
  }

  public void setStatusCallbackUrl(String statusCallbackUrl) {
    this.statusCallbackUrl = statusCallbackUrl;
  }

  public RCSAgent sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @Schema(description = "")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public RCSAgent registrationSid(String registrationSid) {
    this.registrationSid = registrationSid;
    return this;
  }

   /**
   * Get registrationSid
   * @return registrationSid
  **/
  @Schema(description = "")
  public String getRegistrationSid() {
    return registrationSid;
  }

  public void setRegistrationSid(String registrationSid) {
    this.registrationSid = registrationSid;
  }

  public RCSAgent googleRegistrationSid(String googleRegistrationSid) {
    this.googleRegistrationSid = googleRegistrationSid;
    return this;
  }

   /**
   * Get googleRegistrationSid
   * @return googleRegistrationSid
  **/
  @Schema(description = "")
  public String getGoogleRegistrationSid() {
    return googleRegistrationSid;
  }

  public void setGoogleRegistrationSid(String googleRegistrationSid) {
    this.googleRegistrationSid = googleRegistrationSid;
  }

  public RCSAgent addressSid(String addressSid) {
    this.addressSid = addressSid;
    return this;
  }

   /**
   * Get addressSid
   * @return addressSid
  **/
  @Schema(description = "")
  public String getAddressSid() {
    return addressSid;
  }

  public void setAddressSid(String addressSid) {
    this.addressSid = addressSid;
  }

  public RCSAgent user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public RCSAgent carrier(Carrier carrier) {
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @Schema(description = "")
  public Carrier getCarrier() {
    return carrier;
  }

  public void setCarrier(Carrier carrier) {
    this.carrier = carrier;
  }

  public RCSAgent dealer(Dealer dealer) {
    this.dealer = dealer;
    return this;
  }

   /**
   * Get dealer
   * @return dealer
  **/
  @Schema(description = "")
  public Dealer getDealer() {
    return dealer;
  }

  public void setDealer(Dealer dealer) {
    this.dealer = dealer;
  }

  public RCSAgent rcsAgentUseCase(RCSAgentUseCase rcsAgentUseCase) {
    this.rcsAgentUseCase = rcsAgentUseCase;
    return this;
  }

   /**
   * Get rcsAgentUseCase
   * @return rcsAgentUseCase
  **/
  @Schema(description = "")
  public RCSAgentUseCase getRcsAgentUseCase() {
    return rcsAgentUseCase;
  }

  public void setRcsAgentUseCase(RCSAgentUseCase rcsAgentUseCase) {
    this.rcsAgentUseCase = rcsAgentUseCase;
  }

  public RCSAgent rcsAgentBusiness(RCSAgentBusiness rcsAgentBusiness) {
    this.rcsAgentBusiness = rcsAgentBusiness;
    return this;
  }

   /**
   * Get rcsAgentBusiness
   * @return rcsAgentBusiness
  **/
  @Schema(description = "")
  public RCSAgentBusiness getRcsAgentBusiness() {
    return rcsAgentBusiness;
  }

  public void setRcsAgentBusiness(RCSAgentBusiness rcsAgentBusiness) {
    this.rcsAgentBusiness = rcsAgentBusiness;
  }

  public RCSAgent createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public RCSAgent updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RCSAgent rcSAgent = (RCSAgent) o;
    return Objects.equals(this.id, rcSAgent.id) &&
        Objects.equals(this.applicationName, rcSAgent.applicationName) &&
        Objects.equals(this.senderId, rcSAgent.senderId) &&
        Objects.equals(this.name, rcSAgent.name) &&
        Objects.equals(this.description, rcSAgent.description) &&
        Objects.equals(this.logoUrl, rcSAgent.logoUrl) &&
        Objects.equals(this.bannerUrl, rcSAgent.bannerUrl) &&
        Objects.equals(this.privacyUrl, rcSAgent.privacyUrl) &&
        Objects.equals(this.termsOfServiceUrl, rcSAgent.termsOfServiceUrl) &&
        Objects.equals(this.accentColor, rcSAgent.accentColor) &&
        Objects.equals(this.callbackUrl, rcSAgent.callbackUrl) &&
        Objects.equals(this.callbackMethod, rcSAgent.callbackMethod) &&
        Objects.equals(this.fallbackUrl, rcSAgent.fallbackUrl) &&
        Objects.equals(this.fallbackMethod, rcSAgent.fallbackMethod) &&
        Objects.equals(this.status, rcSAgent.status) &&
        Objects.equals(this.repUser, rcSAgent.repUser) &&
        Objects.equals(this.website, rcSAgent.website) &&
        Objects.equals(this.email, rcSAgent.email) &&
        Objects.equals(this.phoneNumber, rcSAgent.phoneNumber) &&
        Objects.equals(this.regulationId, rcSAgent.regulationId) &&
        Objects.equals(this.regulationVersion, rcSAgent.regulationVersion) &&
        Objects.equals(this.usRegulationId, rcSAgent.usRegulationId) &&
        Objects.equals(this.usRegulationVersion, rcSAgent.usRegulationVersion) &&
        Objects.equals(this.comment, rcSAgent.comment) &&
        Objects.equals(this.friendlyName, rcSAgent.friendlyName) &&
        Objects.equals(this.statusNotificationEmail, rcSAgent.statusNotificationEmail) &&
        Objects.equals(this.statusCallbackUrl, rcSAgent.statusCallbackUrl) &&
        Objects.equals(this.sid, rcSAgent.sid) &&
        Objects.equals(this.registrationSid, rcSAgent.registrationSid) &&
        Objects.equals(this.googleRegistrationSid, rcSAgent.googleRegistrationSid) &&
        Objects.equals(this.addressSid, rcSAgent.addressSid) &&
        Objects.equals(this.user, rcSAgent.user) &&
        Objects.equals(this.carrier, rcSAgent.carrier) &&
        Objects.equals(this.dealer, rcSAgent.dealer) &&
        Objects.equals(this.rcsAgentUseCase, rcSAgent.rcsAgentUseCase) &&
        Objects.equals(this.rcsAgentBusiness, rcSAgent.rcsAgentBusiness) &&
        Objects.equals(this.createdAt, rcSAgent.createdAt) &&
        Objects.equals(this.updatedAt, rcSAgent.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, applicationName, senderId, name, description, logoUrl, bannerUrl, privacyUrl, termsOfServiceUrl, accentColor, callbackUrl, callbackMethod, fallbackUrl, fallbackMethod, status, repUser, website, email, phoneNumber, regulationId, regulationVersion, usRegulationId, usRegulationVersion, comment, friendlyName, statusNotificationEmail, statusCallbackUrl, sid, registrationSid, googleRegistrationSid, addressSid, user, carrier, dealer, rcsAgentUseCase, rcsAgentBusiness, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RCSAgent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    bannerUrl: ").append(toIndentedString(bannerUrl)).append("\n");
    sb.append("    privacyUrl: ").append(toIndentedString(privacyUrl)).append("\n");
    sb.append("    termsOfServiceUrl: ").append(toIndentedString(termsOfServiceUrl)).append("\n");
    sb.append("    accentColor: ").append(toIndentedString(accentColor)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    callbackMethod: ").append(toIndentedString(callbackMethod)).append("\n");
    sb.append("    fallbackUrl: ").append(toIndentedString(fallbackUrl)).append("\n");
    sb.append("    fallbackMethod: ").append(toIndentedString(fallbackMethod)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    repUser: ").append(toIndentedString(repUser)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    regulationId: ").append(toIndentedString(regulationId)).append("\n");
    sb.append("    regulationVersion: ").append(toIndentedString(regulationVersion)).append("\n");
    sb.append("    usRegulationId: ").append(toIndentedString(usRegulationId)).append("\n");
    sb.append("    usRegulationVersion: ").append(toIndentedString(usRegulationVersion)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    statusNotificationEmail: ").append(toIndentedString(statusNotificationEmail)).append("\n");
    sb.append("    statusCallbackUrl: ").append(toIndentedString(statusCallbackUrl)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    registrationSid: ").append(toIndentedString(registrationSid)).append("\n");
    sb.append("    googleRegistrationSid: ").append(toIndentedString(googleRegistrationSid)).append("\n");
    sb.append("    addressSid: ").append(toIndentedString(addressSid)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    dealer: ").append(toIndentedString(dealer)).append("\n");
    sb.append("    rcsAgentUseCase: ").append(toIndentedString(rcsAgentUseCase)).append("\n");
    sb.append("    rcsAgentBusiness: ").append(toIndentedString(rcsAgentBusiness)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
