/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: STATFLO-3851-Sms-Activity
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WidgetMetadataUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-27T12:11:22.499844-05:00[America/Toronto]")

public class WidgetMetadataUpdate {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("widgetId")
  private Integer widgetId = null;

  /**
   * Gets or Sets metadata
   */
  @JsonAdapter(MetadataEnum.Adapter.class)
  public enum MetadataEnum {
    @SerializedName("metadata_scope_conversation_right_panel")
    SCOPE_CONVERSATION_RIGHT_PANEL("metadata_scope_conversation_right_panel"),
    @SerializedName("metadata_scope_conversation_sendable")
    SCOPE_CONVERSATION_SENDABLE("metadata_scope_conversation_sendable"),
    @SerializedName("metadata_scope_conversation_action_button")
    SCOPE_CONVERSATION_ACTION_BUTTON("metadata_scope_conversation_action_button"),
    @SerializedName("metadata_scope_dashboard_left")
    SCOPE_DASHBOARD_LEFT("metadata_scope_dashboard_left"),
    @SerializedName("metadata_scope_dashboard_center")
    SCOPE_DASHBOARD_CENTER("metadata_scope_dashboard_center"),
    @SerializedName("metadata_scope_dashboard_right")
    SCOPE_DASHBOARD_RIGHT("metadata_scope_dashboard_right"),
    @SerializedName("metadata_default_expanded")
    DEFAULT_EXPANDED("metadata_default_expanded"),
    @SerializedName("metadata_native_module")
    NATIVE_MODULE("metadata_native_module"),
    @SerializedName("metadata_native_remote")
    NATIVE_REMOTE("metadata_native_remote");

    private String value;

    MetadataEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static MetadataEnum fromValue(String input) {
      for (MetadataEnum b : MetadataEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<MetadataEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MetadataEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public MetadataEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return MetadataEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("metadata")
  private MetadataEnum metadata = null;

  @SerializedName("value")
  private Object value = null;

  public WidgetMetadataUpdate id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public WidgetMetadataUpdate widgetId(Integer widgetId) {
    this.widgetId = widgetId;
    return this;
  }

   /**
   * Get widgetId
   * @return widgetId
  **/
  @Schema(description = "")
  public Integer getWidgetId() {
    return widgetId;
  }

  public void setWidgetId(Integer widgetId) {
    this.widgetId = widgetId;
  }

  public WidgetMetadataUpdate metadata(MetadataEnum metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(required = true, description = "")
  public MetadataEnum getMetadata() {
    return metadata;
  }

  public void setMetadata(MetadataEnum metadata) {
    this.metadata = metadata;
  }

  public WidgetMetadataUpdate value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetMetadataUpdate widgetMetadataUpdate = (WidgetMetadataUpdate) o;
    return Objects.equals(this.id, widgetMetadataUpdate.id) &&
        Objects.equals(this.widgetId, widgetMetadataUpdate.widgetId) &&
        Objects.equals(this.metadata, widgetMetadataUpdate.metadata) &&
        Objects.equals(this.value, widgetMetadataUpdate.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, widgetId, metadata, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetMetadataUpdate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    widgetId: ").append(toIndentedString(widgetId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
