/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: main
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.statflo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WidgetUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-26T16:12:18.121727-05:00[America/Toronto]")

public class WidgetUpdate {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("carrierId")
  private Integer carrierId = null;

  @SerializedName("dealerId")
  private Integer dealerId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("nativeRemote")
  private String nativeRemote = null;

  @SerializedName("nativeModule")
  private String nativeModule = null;

  public WidgetUpdate id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public WidgetUpdate carrierId(Integer carrierId) {
    this.carrierId = carrierId;
    return this;
  }

   /**
   * Get carrierId
   * @return carrierId
  **/
  @Schema(description = "")
  public Integer getCarrierId() {
    return carrierId;
  }

  public void setCarrierId(Integer carrierId) {
    this.carrierId = carrierId;
  }

  public WidgetUpdate dealerId(Integer dealerId) {
    this.dealerId = dealerId;
    return this;
  }

   /**
   * Get dealerId
   * @return dealerId
  **/
  @Schema(description = "")
  public Integer getDealerId() {
    return dealerId;
  }

  public void setDealerId(Integer dealerId) {
    this.dealerId = dealerId;
  }

  public WidgetUpdate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WidgetUpdate label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public WidgetUpdate url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(required = true, description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public WidgetUpdate type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public WidgetUpdate priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @Schema(description = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public WidgetUpdate nativeRemote(String nativeRemote) {
    this.nativeRemote = nativeRemote;
    return this;
  }

   /**
   * Get nativeRemote
   * @return nativeRemote
  **/
  @Schema(description = "")
  public String getNativeRemote() {
    return nativeRemote;
  }

  public void setNativeRemote(String nativeRemote) {
    this.nativeRemote = nativeRemote;
  }

  public WidgetUpdate nativeModule(String nativeModule) {
    this.nativeModule = nativeModule;
    return this;
  }

   /**
   * Get nativeModule
   * @return nativeModule
  **/
  @Schema(description = "")
  public String getNativeModule() {
    return nativeModule;
  }

  public void setNativeModule(String nativeModule) {
    this.nativeModule = nativeModule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetUpdate widgetUpdate = (WidgetUpdate) o;
    return Objects.equals(this.id, widgetUpdate.id) &&
        Objects.equals(this.carrierId, widgetUpdate.carrierId) &&
        Objects.equals(this.dealerId, widgetUpdate.dealerId) &&
        Objects.equals(this.name, widgetUpdate.name) &&
        Objects.equals(this.label, widgetUpdate.label) &&
        Objects.equals(this.url, widgetUpdate.url) &&
        Objects.equals(this.type, widgetUpdate.type) &&
        Objects.equals(this.priority, widgetUpdate.priority) &&
        Objects.equals(this.nativeRemote, widgetUpdate.nativeRemote) &&
        Objects.equals(this.nativeModule, widgetUpdate.nativeModule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, carrierId, dealerId, name, label, url, type, priority, nativeRemote, nativeModule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetUpdate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    carrierId: ").append(toIndentedString(carrierId)).append("\n");
    sb.append("    dealerId: ").append(toIndentedString(dealerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    nativeRemote: ").append(toIndentedString(nativeRemote)).append("\n");
    sb.append("    nativeModule: ").append(toIndentedString(nativeModule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
