/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AccountAction;
import io.swagger.client.model.AccountActionCreate;
import io.swagger.client.model.AccountActionPaginationResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccountActionsApi
 */
@Ignore
public class AccountActionsApiTest {

    private final AccountActionsApi api = new AccountActionsApi();

    /**
     * 
     *
     * Create account action
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountActionCreateTest() throws Exception {
        AccountActionCreate body = null;
        AccountAction response = api.accountActionCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve an account action
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountActionGetTest() throws Exception {
        String id = null;
        AccountAction response = api.accountActionGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search account actions
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void accountActionSearchTest() throws Exception {
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        AccountActionPaginationResponse response = api.accountActionSearch(query, page, perPage, sort);

        // TODO: test validations
    }
}
