/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AuthLoginBody;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * 
     *
     * Get currently logged in user.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void authMeTest() throws Exception {
        User response = api.authMe();

        // TODO: test validations
    }
    /**
     * 
     *
     * Log in.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws Exception {
        AuthLoginBody body = null;
        InlineResponse200 response = api.login(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Log out.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void logoutTest() throws Exception {
        api.logout();

        // TODO: test validations
    }
    /**
     * 
     *
     * Switch active dealer.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void switchDealerTest() throws Exception {
        Integer dealerId = null;
        Integer roleId = null;
        api.switchDealer(dealerId, roleId);

        // TODO: test validations
    }
}
