/*
 * Statflo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CampaignMetadata;
import io.swagger.client.model.CampaignMetadataCreate;
import io.swagger.client.model.CampaignMetadataPaginationResponse;
import io.swagger.client.model.CampaignMetadataUpdate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CampaignMetadataApi
 */
@Ignore
public class CampaignMetadataApiTest {

    private final CampaignMetadataApi api = new CampaignMetadataApi();

    /**
     * 
     *
     * Create a campaign metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMetadataCreateTest() throws Exception {
        CampaignMetadataCreate body = null;
        CampaignMetadata response = api.campaignMetadataCreate(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Remove a campaign metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMetadataDeleteTest() throws Exception {
        String id = null;
        api.campaignMetadataDelete(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Retrieve a campaign metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMetadataGetTest() throws Exception {
        String id = null;
        CampaignMetadata response = api.campaignMetadataGet(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * Search campaign metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMetadataSearchTest() throws Exception {
        List<String> filter = null;
        String query = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        CampaignMetadataPaginationResponse response = api.campaignMetadataSearch(filter, query, page, perPage, sort);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update a campaign metadata.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void campaignMetadataUpdateTest() throws Exception {
        String id = null;
        CampaignMetadataUpdate body = null;
        CampaignMetadata response = api.campaignMetadataUpdate(id, body);

        // TODO: test validations
    }
}
